In [18]:
from keras.callbacks import ModelCheckpoint
from sklearn.model_selection import GridSearchCV
from keras.optimizers import SGD
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import keras
import keras.callbacks
import tensorflow.keras.datasets.fashion_mnist

In [20]:
(x_train,y_train),(x_test,y_test) =  tensorflow.keras.datasets.fashion_mnist.load_data()

4422102/4422102 [==============================] - 2s 0us/step


In [21]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [22]:
print(x_train.shape[0], 'train set samples')
print(y_test.shape[0], 'train set samples')

60000 train set samples
10000 train set samples


In [23]:
print(np.min(x_train))
print(np.max(x_train))

0
255


In [24]:
x_train = x_train.astype('float32')/255
x_test = x_test.astype('float32')/255
print(np.min(x_train))
print(np.max(x_train))
print(x_train[:2])

0.0
1.0
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [25]:
from sklearn.model_selection import train_test_split

In [26]:
np.random.seed(500)

In [35]:
train_x, val_x,train_y, val_y = train_test_split(x_train, y_train, test_size = 0.2, random_state = 500)

In [36]:
test_x, test_y = x_test, y_test

In [37]:
train_x = train_x.reshape(train_x.shape[0],28,28,1)
val_x = val_x.reshape(val_x.shape[0],28,28,1)
test_x = test_x.reshape(test_x.shape[0],28,28,1)

In [38]:
train_y = tf.keras.utils.to_categorical(train_y,10)
val_y = tf.keras.utils.to_categorical(val_y,10)
test_y = tf.keras.utils.to_categorical(test_y,10)


In [39]:
print(train_x.shape)
print(train_y.shape)

(48000, 28, 28, 1)
(48000, 10)


In [40]:
print(train_x.shape[0])
print(val_x.shape[0])
print(test_x .shape[0])

48000
12000
10000


In [41]:
model1 = tf.keras.Sequential()

In [42]:
model1.add(tf.keras.layers.Flatten(input_shape = (28,28,1)))
model1.add(tf.keras.layers.Dense(10,activation='softmax'))

In [43]:
model1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 10)                7850      
                                                                 
Total params: 7850 (30.66 KB)
Trainable params: 7850 (30.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [44]:
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [45]:
model1.fit(train_x, train_y, batch_size = 128, epochs =3, validation_data=(val_x, val_y))

Epoch 1/3
375/375 [==============================] - 1s 2ms/step - loss: 0.7807 - accuracy: 0.7456 - val_loss: 0.5604 - val_accuracy: 0.8117
Epoch 2/3
375/375 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.8206 - val_loss: 0.4934 - val_accuracy: 0.8338
Epoch 3/3
375/375 [==============================] - 1s 2ms/step - loss: 0.4910 - accuracy: 0.8367 - val_loss: 0.4662 - val_accuracy: 0.8398


In [46]:
scores = model1.evaluate(test_x, test_y, verbose = 0)
print(" ACCURACY   :    ",100*scores[1])

 ACCURACY   :     82.56000280380249


In [47]:
model2 = tf.keras.Sequential()

In [51]:
model2.add(tf.keras.layers.Conv2D(filters = 64, kernel_size = 2, padding = 'same', activation = 'relu', input_shape = (28,28,1)))
model2.add(tf.keras.layers.MaxPooling2D(pool_size = 2))
model2.add(tf.keras.layers.Conv2D(filters = 32, kernel_size = 2, padding = 'same', activation = 'relu'))
model2.add(tf.keras.layers.MaxPooling2D(pool_size = 2))
model2.add(tf.keras.layers.Flatten())
model2.add(tf.keras.layers.Dense(128,activation='relu'))
model2.add(tf.keras.layers.Dense(64,activation='relu'))
model2.add(tf.keras.layers.Dense(10,activation='softmax'))

In [52]:
model2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 28, 28, 64)        320       
                                                                 
 max_pooling2d (MaxPooling2  (None, 14, 14, 64)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 14, 14, 32)        8224      
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 7, 7, 32)          0         
 g2D)                                                            
                                                                 
 flatten_1 (Flatten)         (None, 1568)              0         
                                                                 
 dense_1 (Dense)             (None, 128)              

In [53]:
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [57]:
model2.fit(train_x, train_y, batch_size = 256, epochs =10, validation_data=(val_x, val_y))

Epoch 1/10
188/188 [==============================] - 33s 173ms/step - loss: 0.7045 - accuracy: 0.7420 - val_loss: 0.4330 - val_accuracy: 0.8456
Epoch 2/10
188/188 [==============================] - 33s 175ms/step - loss: 0.4100 - accuracy: 0.8529 - val_loss: 0.3989 - val_accuracy: 0.8578
Epoch 3/10
188/188 [==============================] - 32s 172ms/step - loss: 0.3541 - accuracy: 0.8729 - val_loss: 0.3270 - val_accuracy: 0.8847
Epoch 4/10
188/188 [==============================] - 33s 175ms/step - loss: 0.3204 - accuracy: 0.8839 - val_loss: 0.2960 - val_accuracy: 0.8957
Epoch 5/10
188/188 [==============================] - 33s 174ms/step - loss: 0.2935 - accuracy: 0.8933 - val_loss: 0.2801 - val_accuracy: 0.9005
Epoch 6/10
188/188 [==============================] - 33s 175ms/step - loss: 0.2796 - accuracy: 0.8982 - val_loss: 0.2686 - val_accuracy: 0.9043
Epoch 7/10
188/188 [==============================] - 33s 173ms/step - loss: 0.2615 - accuracy: 0.9040 - val_loss: 0.2685 - val_ac

In [58]:
test_score = model2.evaluate(test_x, test_y, verbose = 0)
print(" ACCURACY (TEST)   :    ",100*test_score[1])
train_score = model2.evaluate(train_x, train_y, verbose = 0)
print(" ACCURACY (TRAIN)  :    ",100*train_score[1])

 ACCURACY (TEST)   :     89.6399974822998
 ACCURACY (TRAIN)  :     92.2041654586792
