In [7]:
!pip install Tensorflow

                                              0.0/276.5 MB ? eta -:--:--
                                              0.0/276.5 MB 1.4 MB/s eta 0:03:23
                                              0.1/276.5 MB 1.3 MB/s eta 0:03:30
                                              0.2/276.5 MB 1.7 MB/s eta 0:02:44
                                              0.4/276.5 MB 2.2 MB/s eta 0:02:04
                                              0.6/276.5 MB 2.8 MB/s eta 0:01:38
                                              0.8/276.5 MB 3.1 MB/s eta 0:01:30
                                              1.0/276.5 MB 3.3 MB/s eta 0:01:24
                                              1.2/276.5 MB 3.5 MB/s eta 0:01:19
                                              1.4/276.5 MB 3.4 MB/s eta 0:01:21
                                              1.6/276.5 MB 3.7 MB/s eta 0:01:16
                                              1.8/276.5 MB 3.7 MB/s eta 0:01:15
                                              2


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


  Using cached tensorflow-2.13.0-cp38-cp38-win_amd64.whl (1.9 kB)
                                              0.0/276.5 MB ? eta -:--:--
                                            0.0/276.5 MB 660.6 kB/s eta 0:06:59
                                            0.0/276.5 MB 660.6 kB/s eta 0:06:59
                                            0.0/276.5 MB 247.7 kB/s eta 0:18:36
                                            0.1/276.5 MB 479.1 kB/s eta 0:09:37
                                            0.1/276.5 MB 479.1 kB/s eta 0:09:37
                                            0.1/276.5 MB 386.4 kB/s eta 0:11:56
                                            0.1/276.5 MB 426.7 kB/s eta 0:10:48
                                            0.2/276.5 MB 438.4 kB/s eta 0:10:31
                                            0.2/276.5 MB 389.2 kB/s eta 0:11:51
                                            0.2/276.5 MB 481.4 kB/s eta 0:09:34
                                            0.3/276.5 MB 518.


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
from keras.datasets import mnist

In [33]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [12]:
import numpy as np
new_xtrain =np.reshape(x_train,(60000,784))
new_xtest =np.reshape(x_test,(10000,784))
print(new_xtrain.shape)
print(new_xtest.shape)

(60000, 784)
(10000, 784)


#### NAIVE BAYES MODEL

In [13]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB

In [14]:
model = GaussianNB()
model.fit(new_xtrain, y_train)
pred = model.predict(new_xtest)
acc_score = accuracy_score(y_test, pred)
cm = confusion_matrix(y_test, pred)

In [26]:
print("\nACCURACY  :  \n",acc_score)
print("\n\nCONFUSION MATRIX  :  \n",cm)


ACCURACY  :  
 0.9705


CONFUSION MATRIX  :  
 [[ 969    0    0    0    0    2    5    1    3    0]
 [   0 1124    2    3    0    2    2    1    1    0]
 [   5    0  999    7    2    0    3    9    7    0]
 [   1    0   10  971    0   10    0    8    8    2]
 [   1    0    1    0  958    0    6    0    2   14]
 [   3    0    0   11    0  862    8    2    4    2]
 [   6    3    0    0    3    4  939    0    3    0]
 [   1    3   20    1    0    0    0  989    3   11]
 [   5    0    5    6    4    9    4    4  928    9]
 [   8    5    1    9    8    3    1    4    4  966]]


#### DECISION TREE MODEL

In [27]:
from sklearn.tree import DecisionTreeClassifier
tree_model = DecisionTreeClassifier(random_state =0 )
tree_model.fit(new_xtrain, y_train)

DecisionTreeClassifier(random_state=0)

In [28]:
pred = tree_model.predict(new_xtest)
acc_score = accuracy_score(y_test, pred)
cm = confusion_matrix(y_test, pred)

In [29]:
print("\nACCURACY  :  \n",acc_score)
print("\n\nCONFUSION MATRIX  :  \n",cm)


ACCURACY  :  
 0.8781


CONFUSION MATRIX  :  
 [[ 915    0    4    8    5   11   14    4    8   11]
 [   0 1090    8   11    1    6    8    1    9    1]
 [  15    7  879   33   14    9   11   24   30   10]
 [  11    5   29  865    7   37    4    9   23   20]
 [   5    2    7    5  866    8   14   11   21   43]
 [  13    7    3   50    6  751   23    6   21   12]
 [  16    3   15   10   22   20  842    2   24    4]
 [   2   12   26   13    6    6    4  929    9   21]
 [  10    7   29   41   17   27   16   10  788   29]
 [  14    2   11   20   41    8    9   20   28  856]]


#### RANDOM FOREST

In [30]:
from sklearn.ensemble import RandomForestClassifier
forest_model = RandomForestClassifier(random_state =0 )
forest_model.fit(new_xtrain, y_train)

RandomForestClassifier(random_state=0)

In [31]:
pred =forest_model.predict(new_xtest)
acc_score = accuracy_score(y_test, pred)
cm = confusion_matrix(y_test, pred)

In [32]:
print("\nACCURACY  :  \n",acc_score)
print("\n\nCONFUSION MATRIX  :  \n",cm)


ACCURACY  :  
 0.9705


CONFUSION MATRIX  :  
 [[ 969    0    0    0    0    2    5    1    3    0]
 [   0 1124    2    3    0    2    2    1    1    0]
 [   5    0  999    7    2    0    3    9    7    0]
 [   1    0   10  971    0   10    0    8    8    2]
 [   1    0    1    0  958    0    6    0    2   14]
 [   3    0    0   11    0  862    8    2    4    2]
 [   6    3    0    0    3    4  939    0    3    0]
 [   1    3   20    1    0    0    0  989    3   11]
 [   5    0    5    6    4    9    4    4  928    9]
 [   8    5    1    9    8    3    1    4    4  966]]
