In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


# Extracting and storing train data

In [2]:
train = pd.read_csv("C:/Users/user/Desktop/Sneha's Program/ML Datasets/naive bayes/datatraining.csv")
train.head()

Id            Date  Temperature  Humidity  Light     CO2  HumidityRatio  \
0   1  2/4/2015 17:51        23.18   27.2720  426.0  721.25       0.004793   
1   2  2/4/2015 17:51        23.15   27.2675  429.5  714.00       0.004783   
2   3  2/4/2015 17:53        23.15   27.2450  426.0  713.50       0.004779   
3   4  2/4/2015 17:54        23.15   27.2000  426.0  708.25       0.004772   
4   5  2/4/2015 17:55        23.10   27.2000  426.0  704.50       0.004757   

   Occupancy  
0          1  
1          1  
2          1  
3          1  
4          1

In [3]:
train.shape

(8143, 8)

In [4]:
train.describe()

Id  Temperature     Humidity        Light          CO2  \
count  8143.000000  8143.000000  8143.000000  8143.000000  8143.000000   
mean   4072.000000    20.619084    25.731507   119.519375   606.546243   
std    2350.825954     1.016916     5.531211   194.755805   314.320877   
min       1.000000    19.000000    16.745000     0.000000   412.750000   
25%    2036.500000    19.700000    20.200000     0.000000   439.000000   
50%    4072.000000    20.390000    26.222500     0.000000   453.500000   
75%    6107.500000    21.390000    30.533333   256.375000   638.833333   
max    8143.000000    23.180000    39.117500  1546.333333  2028.500000   

       HumidityRatio    Occupancy  
count    8143.000000  8143.000000  
mean        0.003863     0.212330  
std         0.000852     0.408982  
min         0.002674     0.000000  
25%         0.003078     0.000000  
50%         0.003801     0.000000  
75%         0.004352     0.000000  
max         0.006476     1.000000

In [5]:
train_df = train.drop('Occupancy', axis=1)
train_df.head(3)

Id            Date  Temperature  Humidity  Light     CO2  HumidityRatio
0   1  2/4/2015 17:51        23.18   27.2720  426.0  721.25       0.004793
1   2  2/4/2015 17:51        23.15   27.2675  429.5  714.00       0.004783
2   3  2/4/2015 17:53        23.15   27.2450  426.0  713.50       0.004779

In [6]:
traindf1 = train_df.drop('Date', axis=1)
traindf1.head(3)

Id  Temperature  Humidity  Light     CO2  HumidityRatio
0   1        23.18   27.2720  426.0  721.25       0.004793
1   2        23.15   27.2675  429.5  714.00       0.004783
2   3        23.15   27.2450  426.0  713.50       0.004779

In [7]:
train_df1 = traindf1.drop('Id', axis=1)
train_df1.head(3)

Temperature  Humidity  Light     CO2  HumidityRatio
0        23.18   27.2720  426.0  721.25       0.004793
1        23.15   27.2675  429.5  714.00       0.004783
2        23.15   27.2450  426.0  713.50       0.004779

In [8]:
train_target = train['Occupancy']
train_target.head()

0    1
1    1
2    1
3    1
4    1
Name: Occupancy, dtype: int64

# Extracting and storing test data

In [9]:
test = pd.read_csv("C:/Users/user/Desktop/Sneha's Program/ML Datasets/naive bayes/datatest2.csv")

In [10]:
test.head()

date  Temperature   Humidity       Light          CO2  \
0  2/11/2015 14:48      21.7600  31.133333  437.333333  1029.666667   
1  2/11/2015 14:49      21.7900  31.000000  437.333333  1000.000000   
2  2/11/2015 14:50      21.7675  31.122500  434.000000  1003.750000   
3  2/11/2015 14:51      21.7675  31.122500  439.000000  1009.500000   
4  2/11/2015 14:51      21.7900  31.133333  437.333333  1005.666667   

   HumidityRatio  Occupancy  
0       0.005021          1  
1       0.005009          1  
2       0.005022          1  
3       0.005022          1  
4       0.005030          1

In [11]:
test_data= test.drop('Occupancy', axis =1)

In [12]:
test_df1= test_data.drop('date', axis =1)

In [13]:
test_df1.head()

Temperature   Humidity       Light          CO2  HumidityRatio
0      21.7600  31.133333  437.333333  1029.666667       0.005021
1      21.7900  31.000000  437.333333  1000.000000       0.005009
2      21.7675  31.122500  434.000000  1003.750000       0.005022
3      21.7675  31.122500  439.000000  1009.500000       0.005022
4      21.7900  31.133333  437.333333  1005.666667       0.005030

In [14]:
test.shape

(9752, 7)

In [15]:
test_target = test['Occupancy']

In [16]:
sc = StandardScaler()

In [17]:
train_df1 = sc.fit_transform(train_df1)
train_df1

array([[2.51847007, 0.27852622, 1.57376283, 0.36494808, 1.09175673],
       [2.48896731, 0.27771261, 1.59173515, 0.34188106, 1.080555  ],
       [2.48896731, 0.27364453, 1.57376283, 0.34029023, 1.07588869],
       ...,
       [0.47294534, 1.87375407, 1.60970748, 0.61073113, 2.033527  ],
       [0.47294534, 1.90358662, 1.60970748, 0.68019732, 2.06381051],
       [0.47294534, 1.89273842, 1.68159679, 0.68231843, 2.05279885]])

In [18]:
test_df1 = sc.fit_transform(test_df1)
test_df1

array([[ 7.42897500e-01,  3.14074332e-01,  1.50936314e+00,
         9.30527184e-01,  8.14063358e-01],
       [ 7.72290797e-01,  2.80341614e-01,  1.50936314e+00,
         8.30666611e-01,  7.90652817e-01],
       [ 7.50245824e-01,  3.11333549e-01,  1.49335371e+00,
         8.43289436e-01,  8.15114290e-01],
       ...,
       [-1.09508097e-01, -5.43158393e-01,  1.44292400e+00,
         2.58608082e+00, -6.62878117e-01],
       [-1.09508097e-01, -4.72952171e-01,  1.42011056e+00,
         2.95803340e+00, -5.82519504e-01],
       [-1.73267669e-03, -4.53345028e-01,  1.37328297e+00,
         3.73896552e+00, -5.04835305e-01]])

In [19]:
le = LabelEncoder()
train_target = le.fit_transform(train_target)
test_target = le.fit_transform(test_target)

In [20]:
model = GaussianNB()

In [21]:
model.fit(train_df1, train_target)

GaussianNB()

In [22]:
y_pred = model.predict(test_df1)

In [23]:
(1682 +727)

2409

In [25]:
2665 - (1682 +727)

256

In [26]:
confusion_matrix(test_target, y_pred)

array([[7635,   68],
       [  15, 2034]], dtype=int64)

In [28]:
model.score(train_df1, train_target)

0.9788775635515167

In [29]:
mean_squared_error(y_pred, test_target)

0.008511074651353569